import asyncio
from datetime import datetime
from typing import List
from app.core.database import get_database
from app.models.domain.user import User, UserRole
from app.services.notifications.email import send_otp_email # Reusing/Updating email service
from app.core.logging_config import logger
from app.core.config import settings

# Helper to send generic HTML email (need to add this to email_service or here)
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

def send_html_email(to_email: str, subject: str, html_content: str):
    """Send generic HTML email."""
    if not settings.SMTP_USER or not settings.SMTP_PASSWORD:
        logger.warning(f"SMTP not configured. Skipping email to {to_email}")
        return

    try:
        msg = MIMEMultipart()
        msg['From'] = f"{settings.EMAILS_FROM_NAME} <{settings.EMAILS_FROM_EMAIL or settings.SMTP_USER}>"
        msg['To'] = to_email
        msg['Subject'] = subject
        msg.attach(MIMEText(html_content, 'html'))

        server = smtplib.SMTP(settings.SMTP_SERVER, settings.SMTP_PORT)
        server.starttls()
        server.login(settings.SMTP_USER, settings.SMTP_PASSWORD)
        server.sendmail(settings.SMTP_USER, to_email, msg.as_string())
        server.quit()
    except Exception as e:
        logger.error(f"Failed to send email: {e}")

async def generate_executive_briefing():
    """
    Generates and sends the Weekly Executive Briefing.
    Aggregates Risk, Upsell, and Operational data.
    Sends to Directors and Heads.
    """
    logger.info("📊 Generating Executive Briefing...")
    db = await get_database()
    
    # 1. Fetch Recipients (Directors & Heads)
    recipients = []
    async for user in db.users.find({"role": {"$in": ["director", "head"]}}):
        recipients.append(user["email"])
        
    if not recipients:
        logger.info("No Executives found to send briefing.")
        return

    # 2. Aggregations
    
    # A. Projects at Risk
    high_risk_projects = []
    async for p in db.projects.find({
        "intelligence.risk_analysis.risk_level": "High"
    }):
        high_risk_projects.append({
            "name": p["name"],
            "client_id": p["client_id"],
            "score": p.get("intelligence", {}).get("risk_analysis", {}).get("risk_score", 0),
            "summary": p.get("intelligence", {}).get("risk_analysis", {}).get("summary", "No details")
        })

    # B. Top Upsell Opportunities
    upsell_leads = []
    async for p in db.projects.find({
        "intelligence.upsell_opportunities.0": {"$exists": True}
    }):
        opportunities = p.get("intelligence", {}).get("upsell_opportunities", [])
        for opp in opportunities:
            if opp.get("potential_value") == "High":
                upsell_leads.append({
                    "project": p["name"],
                    "pitch": opp.get("title")
                })
                
    # C. Operational Stats
    total_projects = await db.projects.count_documents({})
    active_projects = await db.projects.count_documents({"status": "Active"})
    
    # 3. Build HTML Output
    html = f"""
    <html>
    <body style="font-family: Arial, sans-serif; color: #333;">
        <h2 style="color: #2C3E50;">Weekly Executive Briefing</h2>
        <p>Here is your Monday morning overview of department performance.</p>
        
        <h3 style="background-color: #E74C3C; color: white; padding: 10px;">🚩 High Risk Projects ({len(high_risk_projects)})</h3>
        <ul>
    """
    
    if high_risk_projects:
        for p in high_risk_projects:
            html += f"<li><strong>{p['name']}</strong> (Score: {p['score']}): {p['summary']}</li>"
    else:
        html += "<li>No high-risk projects detected.</li>"
        
    html += f"""
        </ul>
        
        <h3 style="background-color: #27AE60; color: white; padding: 10px;">💰 High Value Upsell Opportunities</h3>
        <ul>
    """
    
    if upsell_leads:
        for opp in upsell_leads[:5]: # Top 5
            html += f"<li><strong>{opp['project']}</strong>: {opp['pitch']}</li>"
    else:
        html += "<li>No high-value upsell opportunities identified.</li>"
        
    html += f"""
        </ul>
        
        <h3 style="background-color: #34495E; color: white; padding: 10px;">📊 Operational Snapshot</h3>
        <p><strong>Total Projects:</strong> {total_projects}</p>
        <p><strong>Active Projects:</strong> {active_projects}</p>
        
        <hr>
        <p style="font-size: 12px; color: #777;">Generated by Project Nexus AI</p>
    </body>
    </html>
    """
    
    # 4. Send Emails
    for email in recipients:
        send_html_email(email, f"Executive Briefing - {datetime.utcnow().strftime('%Y-%m-%d')}", html)
        
    logger.info(f"✅ Executive Briefing sent to {len(recipients)} recipients.")
